# Generated by Django 3.1.5 on 2021-01-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='content',
            new_name='reply',
        ),
    ]
